name: C/C++ CMake CI

on: [push]
jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check CMake version
      run: cmake --version
    - name: Generate project buildsystem
      run: cmake  -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCATCH2TEST=ON
    - name: Build project
      run: cmake --build build --parallel 4
    - name: Install project
      run: cmake --install build